---

    - name: Installing webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           github_user: "opensource-spraakherkenning-nl"
           github_repo: "asr_nl"
           metadata:
              identifier: "asr_nl"

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: asr_nl
          clam: asr_nl
          uwsgi: asr_nl

    - name: link python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - asr_nl

    - name: Register webservice metadata
      include_role:
          name: lamachine-register
      vars:
          update: "{{item}}"
          metadata: #add entrypoint metadata to registry
              identifier: "{{item}}"
              entryPoints:
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "WUI", mediatorApplication: "#clam" }
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "REST", specification: "{{lm_base_url}}/{{item}}/info",  mediatorApplication: "#clam" }
      when: '"all" in services or item in services'
      with_items:
        - asr_nl


