---
#################################################################################################################
#                                   LaMachine Installation Manifest
#
# INSTRUCTIONS: Comment or remove categories/roles you do not want to install, dependencies will be automatically
# resolved even when not explicitly mentioned). Instead of editing this file, you can always add additional
# packages using lamachine-add once the system is installed.
#
# NOTE: ensure that all enabled roles are lined up with the same amount of spaces!
#       (all hyphens must be vertically on the same column!)
#       (don't use tabs)
#
################################################################################################################
- hosts: all
  ##1##
  roles:
      - lamachine-core                   ## The LaMachine core ##
                                              #you always need this or nothing works; already includes Python 3
      - python-core                      ## Core 3rd party scientific python packages ###
                                              #(provides: numpy, scipy, pandas, matplotlib, scikit-learn, nltk, and more)
      - java-core                        ## Java 8, Maven ##
      - r-core                           ## R with core R packages ##
      - nodejs-core                      ## Node.js with NPM ##
      - extra-utils                      ## Extra command-line utilities useful for data science
                                              #(provides: jq, ack, graphviz, gnuplot, glances, csvkit, xmlstarlet and a lot more)
      - languagemachines-basic           ## Generic & Dutch NLP tools written in C++ ##
                                              #by the Language Machines Research group,
                                              #Centre for Language and Speech Technology, Radboud University Nijmegen
                                              #(provides: timbl, frog, ucto, folia, mbt, wopr, Colibri Core)
      - languagemachines-python          ## Python-based NLP tools and libraries and web applications/services ##
                                              #by the Language Machines Research group,
                                              #Centre for Language and Speech Technology, Radboud University Nijmegen
                                             #(this includes pynlpl, pynlpl.formats.folia, CLAM, foliadocserve, FLAT, babelente)
      - languagemachines-python-bindings ## Provides Python bindings to C++ software ##
                                             #(provides python-ucto, python-frog, python-timbl, colibricore)
      - nextflow                         ## Nextflow: Data-driven computational pipelines ##
      - languagemachines-pipelines       ## NLP Pipelines
                                              #by the Language Machines Research group,
                                              #(provides: aNtiLoPe, nederlab-pipeline)
      - labirinto                        ## Labirinto provides the LaMachine Portal website, providing access to all installed webservices ##
                                              #by the Language Machines Research group,
                                              #Centre for Language and Speech Technology, Radboud University Nijmegen
      - jupyter                          ## Jupyter Lab Environment, provides a powerful scripting IDE and terminal from the web-browser
                                              #CAUTION: Allows arbitrary code execution over network!!! (password protected)
                                              #Once installed, change the default password by running: lamachine-passwd lab
      - python-course                    ## Python Course for the Humanities by Folgert Karsdorp et al. ##
                                              # http://www.karsdorp.io/python-course/
                                              #(requires jupyter)
     # - cltl-vu-python                   ## Python software by the Computational Lexicology & Terminology Lab, VU Amsterdam
                                             #(provides KafNafParserPy)
     # - go-core                          ## Go compiler and standard library
     # - rust-core                        ## Rust, Rustup and Cargo ##
     # - julia-core                       ## Julia compiler and standard library
     # - languagemachines-rust            ## NLP tools written in Rust (sesdiff, ssam)
     # - piccl                            ## PICCL: Workflows for Post-OCR correction and normalisation and pseudo-modernisation of historical text. ##
                                             # [2.2GB! - not supported on Mac OS X]
                                             # (provides TICCL-Tools)
     # - alpino                           ## ALPINO: Dependency parser for Dutch ##
                                             # by Groningen University
                                             # [1.6GB! - only supported on Debian/Ubuntu for now]
     # - tscan                            ## T-Scan: Software for feature extraction for readability prediction ##
                                             # by Utrecht University, Tilburg University & Radboud University
                                             # [requires Alpino, so only supported on Debian/Ubuntu]
     # - gecco                            ## Generic software for context-aware spelling correction ##
                                             # Centre for Language and Speech Technology, Radboud University Nijmegen
                                             # [Not supported on Mac OS X]
     # - valkuil                          ## A Dutch Spelling corrector ##
                                             # Centre for Language and Speech Technology, Radboud University Nijmegen
                                             # [1.2GB! - Not supported on Mac OS X, requires at least 32GB RAM]
     # - tensorflow                       ## Tensorflow Deep Learning Library for Python (by Google) ##
                                             #(>250MB)
     # - spacy                            ## spaCy is a library for advanced Natural Language Processing in Python and Cython ##
                                             #(>500MB)
     # - pytorch                          ## Deep-learning library for Python; also adds extras like FLAIR and Huggingface's Transformers
     # - kaldi                            ## Kaldi Automatic Speech Recognition Toolkit
                                             #(>7GB !!!! - Not supported on Mac OS X)
     # - corenlp                          ## Stanford CoreNLP (including all models)
                                             #(>2GB)
     # - freeling                         ## FreeLing, a multilingual open source language analysis tool suite
                                            # by TALP Research Center, Universitat Politècnica de Catalunya
     # - moses                            ## Moses MT Decoder
                                            # 7GB - Debian/Ubuntu only for now
     # - oersetter                        ## Frisian<->Dutch Machine Translation system
                                            # 2GB? - Debian/Ubuntu only for now
     # - glem                             ## Lemmatiser for ancient greek
                                            # ('Unraveling the Language of Perspective' project)
                                            # Radboud University Nijmegen
     # - phonetisaurus                    ## Grapheme to Phoneme conversion
                                             #(not supported on Mac OS X)
     # - spotlight                        ## DBPedia Spotlight Named Entity recogniser and linker webservice
                                              #(Models may take up several GB!, set the spotlight_languages variable
                                              #to customise installed languages, we only ship a subset by default)
                                              #(Needs to be started manually using 'spotlight' and a language code parameter)
     # - fasttext                         ## Library for efficient text classification and representation learning
     # - g2pservice                       ## Grapheme to Phoneme conversion webservice
                                             #(Authorization is required for this
                                             #contact l.tenbosch@let.ru.nl to request access)
     # - t2t                              ## Text 2 text translitteration
                                             #(Authorization is required for this
                                             #contact l.tenbosch@let.ru.nl to request access)
     # - kaldi_nl                         ## Dutch models for Kaldi
                                             #(will download several big models, multiple GB)
                                             #(Authorization is required for this
                                             #contact h.vandenheuvel@let.ru.nl to request access and)
                                             #provide a public SSH key (you will need to install the private key in the VM yourself)
     # - oralhistory                      ## Dutch ASR webservice (relies on kaldi_nl)
     # - fy_nl_ASR                        ## Frisian-Dutch Speech Recognition system with webservice
                                             #(>9GB !!!! - Not supported on Mac OS X)
                                             #Relies on kaldi, another 7GB!!
                                             #Authorization is required for this; ensure to
                                             #set fame_user and fame_password in your LaMachine configuration
                                             #contact h.vandenheuvel@let.ru.nl to request access
     # - fame_align                       ## Frisian-Dutch Forced Alignment system with webservice
                                             #(>2GB !!!! - Not supported on Mac OS X)
                                             #Relies on kaldi, another 7GB!!
                                             #Authorization is required for this; ensure to
                                             #set fame_user and fame_password in your LaMachine configuration
                                             #contact h.vandenheuvel@let.ru.nl to request access
     # - forcedalignment                  ## Dutch Forced Alignment system with webservice
                                             #(>2GB !!!! - Not supported on Mac OS X)
                                             #Relies on kaldi, another 7GB!!
                                             #Authorization is required for this; ensure to
                                             #set fame_user and fame_password in your LaMachine configuration
                                             #contact h.vandenheuvel@let.ru.nl to request access
     # - eng_ASR                          ## English Speech Recognition system with webservice
                                             #(Not supported on Mac OS X)
                                             #Relies on kaldi, another 7GB!!


# NOTE: ensure that all enabled roles are lined up with the same amount of spaces!
#       (all hyphens must be vertically on the same column!)
#       (don't use tabs)






