---

    - name: Checking whether virtualenv environment exists
      stat:
         path: "{{ local_prefix }}"
      changed_when: false
      register: virtualenv

    - when: virtualenv.stat.isdir is not defined or not virtualenv.stat.isdir
      block:
           - name: Creating bare virtualenv environment for LaMachine
             shell: "{{python_bin}} -m venv --copies --upgrade-deps {{ local_prefix }}"

    - name: Adapting activation script for virtualenv (1/2)
      blockinfile:
        dest: "{{local_prefix}}/bin/activate"
        block: |
          if [ -z "$LM_PREFIX" ]; then
              if [ -e "{{local_prefix}}/bin/lamachine-{{ conf_name }}-activate" ]; then
                source "{{local_prefix}}/bin/lamachine-{{ conf_name }}-activate"
              else
                source $(which lamachine-{{ conf_name }}-activate)
                if [ $? -ne 0 ]; then
                    echo "WARNING: Can't locate the full activation script lamachine-{{conf_name}}-activate ,">&2
                    echo "         Unable to activate the environment!">&2
                    return 1
                fi
              fi
              return 0
          fi
        marker: '# {mark} LAMACHINE MANAGED BLOCK - ensure environment is ready'
        insertafter: "# you cannot run it directly"
        create: yes
        mode: u+rwx

    - name: Adapting activation script for virtualenv (2/2)
      blockinfile:
        dest: "{{local_prefix}}/bin/activate"
        block: |
          export LD_LIBRARY_PATH={{local_prefix}}/lib/
          for f in $VIRTUAL_ENV/bin/activate.d/*.sh; do
            if [ ! -z "$f" ]; then
                source $f
            fi
          done
        marker: '# {mark} LAMACHINE MANAGED BLOCK - lamachine environment'
        insertafter: EOF
        create: yes
        mode: u+rwx

    - name: Adding activate.d directory for extra activation scripts (local)
      file:
        path: "{{local_prefix}}/bin/activate.d"
        state: directory
      when: locality == "local"
